### PR TITLE
UHM-5311: Add ART treatment reason and "Has the patient started or wi…

### PR DESCRIPTION
**Pull request by brandones**
…ll start prophylaxis (PEP)?" questions to PIH EMR plan form version 3

https://pihemr.atlassian.net/browse/UHM-5311

I have omitted the message codes in favor of plain French text since this is just for a legacy form. Let me know if you'd rather I use message codes in this case as well.

Screenshot from 2021-03-08 11-44-15

### CODE REVIEW

**Review by lnball — CHANGES_REQUESTED** [review]
@brandones I would recommend switching to this CIEL concept which is already in PIH EMR:  https://concepts.pih-emr.org/openmrs/dictionary/concept.htm?conceptId=10964.  I changed the datatype from boolean to coded, but it's really the same as the one you newly created.  Can you add the message prop?  It's a quick detail.

**Comment by brandones** [comment]
@mogoodrich I'm trying to make the change Ellen asked for and now getting an NPE from HFE. I'm looking into it. Let me know if you need this change with urgency.

**Comment by lnball** [comment]
I'll recreate the hiv mds and that should fix it.

e
________________________________

**Comment by mogoodrich** [comment]
no urgency @brandones

**Comment by brandones** [comment]
https://github.com/PIH/openmrs-config-pihemr/pull/140

**Review by lnball — APPROVED** [review]
Thanks @brandones .  Looks good.  I won't squash until you debug the NPE.

**Comment by brandones** [comment]
The NPE is fixed, and this HFE code won't produce it. Thanks for the review, @lnball .

**Pull request merged**
