### PR TITLE
UHM-5676 Fix gestational age calculation

### PR DESCRIPTION
**Pull request by brandones**
https://pihemr.atlassian.net/browse/UHM-5676

Screenshot from 2021-08-04 18-05-44

### CODE REVIEW

**Comment by brandones** [comment]
I've filed bugs against [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1724112) and [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1236819) about the fact that they don't support native date internationalization for `ht`.

**Comment by lnball** [comment]
@brandones I didn't see an explanation here or on the ticket.  Can you provide a sentence about your code fix(es)?  I'm happy to review the code.

**Comment by brandones** [comment]
After reading what's written in the ticket, are there parts that are unclear? The code fixes the EDD calculation, the problem where the wrong widget is updated, adds date internationalization (doesn't work for Haiti yet), and makes the gestational age calculation give answers in the format Meredith asked for (e.g. "28 5/7 weeks"). I actually wasn't able to reproduce the error she saw, exactly, but hopefully this fixes things for her. I see

Screenshot from 2021-08-05 12-43-22

Whereas for those parameters Meredith saw "40 weeks." Fingers crossed.

Please leave questions/comments in the code if you're not sure about anything! Happy to talk about it.

**Comment by brandones** [comment]
Oh, and I'd forgotten to attach the screenshot of my work! Sorry about that, that probably would have helped.

**Comment by brandones** [comment]
Here's what Meredith's use case looks like with my code:
Screenshot from 2021-08-05 12-53-06

**Comment by brandones** [comment]
Filed bugs against CLDR about `ht` language handling:

https://unicode-org.atlassian.net/browse/CLDR-14955
https://unicode-org.atlassian.net/browse/CLDR-14956

Shoutout to PIH for being pre-approved as a domain for contributing to the Unicode Jira. Pretty fancy. We should take advantage of that and make the internet better for users in countries where we work.

**Review by lnball — APPROVED** [review]
@brandones Looks fine for the HIV form.  I approve.  Please squash.  We'll test this on the HIV form before using the same function on other production forms (ie. Ob/gyn, primary care, etc)

**Comment by brandones** [comment]
Oh yeah! Good thing that reminded me that we're already using this on the PMTCT form! So I've updated that as appropriate.

**Pull request merged**
