### PR TITLE
UHM-4911: Medical Record Locations and Visit Locations should be assi…

### PR DESCRIPTION
**Pull request by mogoodrich**
…gned on a per-server basis

https://pihemr.atlassian.net/browse/UHM-4911

### CODE REVIEW

**Comment by mogoodrich** [comment]
So @brandones I was wrong about having multiple medical record locations on a single server... we have bean on the Haiti single-server sites used to automatically assign a dossier number on patient creation and they depend on having a single Medical Record Location.

Just to be safe, I pulled out the Visit Location on a server-by-server basis as well.

**Review by cioan — APPROVED** [review]
Looks good @mogoodrich ! Thanks!

**Comment by mogoodrich** [comment]
Going to go ahead and merge this in, as @jmbabazi  is looking to do a new release...

**Comment by jmbabazi** [comment]
Thanks @mogoodrich

**Pull request merged**
