### PR TITLE
Uhm 5749

### PR DESCRIPTION
**Pull request by louidorjp**
@mogoodrich Please review this PR

### CODE REVIEW

**Comment by mogoodrich** [comment]
Thanks @louidorjp !  I need to get myself back up to speed on the these forms, but should be able to look at this tomorrow!

**Review by mogoodrich — APPROVED** [review]
Looks like this is mainly layout changes?  Looks good to me, thanks @louidorjp !

Let me know if you need me to merge this in.

**Comment by louidorjp** [comment]
> Looks like this is mainly layout changes? Looks good to me, thanks @louidorjp !
> 
> Let me know if you need me to merge this in.

Yes, these are layout changes. you can merge

**Comment by mogoodrich** [comment]
Merged, thanks @louidorjp !  Though we still need to figure out why you don't have merge rights on this repo....

**Pull request merged**
