### PR TITLE
 UHM-5691-CD - Default to showing contacts with data for PMTCT and HIV

### PR DESCRIPTION
**Pull request by louidorjp**
@mogoodrich @brandones 
Please review this PR

### CODE REVIEW

**Comment by brandones** [comment]
Hi @louidorjp , maybe we should do a pair programming session about this? Are you free tomorrow after 12pm Boston time, Wednesday after 11:30am, or Thursday after 12:30?

**Comment by louidorjp** [comment]
Hello @brandones!  I will be available at 12 pm.

**Comment by mogoodrich** [comment]
Thanks @brandones  and @louidorjp

**Review by brandones — APPROVED** [review]
Worked on this doing pair programming with @louidorjp . Thanks @louidorjp !

**Pull request merged**
