### PR TITLE
Changes to key population answers

### PR DESCRIPTION
**Pull request by jmbabazi**

### CODE REVIEW

**Review by mogoodrich — APPROVED** [review]
i didn't review all the concepts in detail, but generally LGTM!

**Comment by jmbabazi** [comment]
Thanks @mogoodrich, I believe there is no hurry here. We can wait to hear from @lnball.

**Review by lnball — CHANGES_REQUESTED** [review]
@jmbabazi Wrap these in a repeat/template.  Easier for readability and updates.  The only changese are the mode/cId.  You can use the previous render lines, but change the conceptId, replace the answers with u/n/u, and format in a table/rows/cells.

**Comment by jmbabazi** [comment]
@lnball , be

**Pull request closed without merging**
