### PR TITLE
Display the information of the person who presented for the last medi…

### PR DESCRIPTION
**Pull request by louidorjp**
@mogoodrich please review this PR.

Screenshot from 2022-10-24 10-36-40

### CODE REVIEW

**Review by mogoodrich — APPROVED** [review]
Looks good to me, though I defer to @lnball  and @dmdesimone  for reviews of the SQL queries.

**Comment by louidorjp** [comment]
@dmdesimone the query is updated

**Comment by dmdesimone** [comment]
> @dmdesimone the query is updated

looks good!

**Comment by louidorjp** [comment]
> 
@dmdesimone if everything is ok, you can merge it. So it will be available for testing

**Pull request merged**
