### PR TITLE
Adding the date of the ARV coating on the patient's dashboard

### PR DESCRIPTION
**Pull request by louidorjp**
@lnball please review this PR

### CODE REVIEW

**Comment by lnball** [comment]
@louidorjp Can you resolve conflicts on the branch?

**Comment by lnball** [comment]
I'm confused about the pull request.  We want 2 things:  

- **HAI-717:  ART start date on the dashboard.**  I reviewed, approved, and closed the pull request.  
- **HAI-744:  Current ARTs dispensed**.  I don't see code for this.  This PR doesn't include the check for "Medication category" (PIH:1535) with ARV #1(PIH:3013), ARV #2(PIH:2848), or ARV #3(PIH:13960)

Can you resolve the conflicting files and a new PR for HAI-744.

FYI @louidorjp @mogoodrich @ljoedavessenn

**Comment by louidorjp** [comment]
@lnball I have resolved the conflict and made some updates

**Review by lnball — APPROVED** [review]
Looks good Louidor.  Assign to me for testing.

**Pull request merged**
