### PR TITLE
HAI-697: Add validation to HIV return visit date

### PR DESCRIPTION
**Pull request by louidorjp**
Please review this PR
@lnball

### CODE REVIEW

**Comment by lnball** [comment]
@louidorjp I think your code restricts "return visit date" to be within 12 months of the current date.  Is that correct?

This could be a problem if a form is back entered.  For example, the current date is "11 Jul 2022" but the encounter date for the HIV form is "1 Jan 2020" and the return visit date is "1 July 2020".  Will an error message appear?  

I think you want to use encounter date instead of current date for your calculations.

**Comment by mogoodrich** [comment]
Hey @louidorjp , how are you?

So the the

**Comment by lnball** [comment]
FYI @mogoodrich.  Spoke to @louidorjp.  He figured out the code and will push fixes to the branch.  We'll review.

**Comment by mogoodrich** [comment]
oh, thanks @lnball @louidorjp ... I got distracted, but I'm in the midst of doing a review, will go ahead and finish that anyway!

**Review by mogoodrich — APPROVED** [review]
Thanks @louidorjp !  There are a few things that I think will need to be fixed, but I think it will easier for me to comment on them via a follow-up review... I also want to merge so I can test some of my changes, so I will test merge this now.

FYI, there are some utility JavaScript functions provided by HTML Form Entry that can come in helpful when writing this code:

https://wiki.openmrs.org/display/docs/HTML+Form+Entry+JavaScript+Reference

**Pull request merged**
